name: food_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2
  equatable: ^2.0.5
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  firebase_storage: ^11.6.0
  cloud_firestore: ^4.15.0
  firebase_messaging: ^14.7.10

  # Auth externes
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.3

  # Utilitaires
  connectivity_plus: ^4.0.2
  http: ^0.13.6
  image_picker: ^1.0.4
  json_annotation: ^4.9.0
  csv: ^5.0.0
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/restaurants.json