name: food_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  image_picker: ^1.0.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/success_order.png
    - assets/images/empty_order.png
    - assets/images/loading_anim.gif
    - assets/images/delivery_in_progress.png
    - assets/images/Loading-bar.gif
    - assets/images/Hourglass.gif
    - assets/images/Burger Tama.png
    - assets/images/Cherry Healthy.png
    - assets/images/Healthy Noodle.png
    - assets/images/pizza.png
    - assets/images/sushi.png
    - assets/images/table_a_manger.png
    - assets/images/tacos.png