// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdiP6NvC6AcQrNYm5fiQZmp6P6mDzGklg',
    appId: '1:220486019687:web:97935a98a1a41a1b1182c2',
    messagingSenderId: '220486019687',
    projectId: 'foodmarket-6fdce',
    authDomain: 'foodmarket-6fdce.firebaseapp.com',
    storageBucket: 'foodmarket-6fdce.firebasestorage.app',
    measurementId: 'G-54LSV6MJN0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF2A-sRGSTLM5_Q5KOmieAdhtakEZICMk',
    appId: '1:220486019687:ios:6b4d26f3af1e86e81182c2',
    messagingSenderId: '220486019687',
    projectId: 'foodmarket-6fdce',
    storageBucket: 'foodmarket-6fdce.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdiP6NvC6AcQrNYm5fiQZmp6P6mDzGklg',
    appId: '1:220486019687:web:c0c6eb91e48d5eb51182c2',
    messagingSenderId: '220486019687',
    projectId: 'foodmarket-6fdce',
    authDomain: 'foodmarket-6fdce.firebaseapp.com',
    storageBucket: 'foodmarket-6fdce.firebasestorage.app',
    measurementId: 'G-MRGV4EELC1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF2A-sRGSTLM5_Q5KOmieAdhtakEZICMk',
    appId: '1:220486019687:ios:6b4d26f3af1e86e81182c2',
    messagingSenderId: '220486019687',
    projectId: 'foodmarket-6fdce',
    storageBucket: 'foodmarket-6fdce.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCismXtjA9Gpri_R7EvNBJFxatgG8BLjSM',
    appId: '1:220486019687:android:07cd928267bb27911182c2',
    messagingSenderId: '220486019687',
    projectId: 'foodmarket-6fdce',
    storageBucket: 'foodmarket-6fdce.firebasestorage.app',
  );

}